### ISSUE TITLE
[feature request] a couple of things

### ISSUE THREAD

**Issue by Zygus42** [Gollorum/Signpost#11]
When you enter a location name on the signposts that doesn't correspond to a waypoint name, still allow a sign of that name on the post.  That way you can use them everywhere as decoration and location helpers, without needing to have all of them as teleports.

At the end of entering names in the waystone and the signpost, allow Enter to finish the process instead of/as well as Esc.  It's more logical.

**Comment by Zygus42** [comment]
Forgot about this one :)

Just a thought, but how about adding a config option for expensive and hideously expensive recipes, for those modpacks / servers where cheap teleportation items are not appropriate ?  Expensive might use the same recipe for signs, but have 6 ender pearls in it as well, and only makes 1 sign.  Hideously expensive might use a nether star instead of the wooden plank or the top sign.

**Comment by Zygus42** [comment]
Another idea, sort of associated with #1 above:  allow the typing in of x,y,z coordinates to point the signs instead of using the tool to swivel the signs.

**Comment by Gollorum** [comment]
Finaly got some time for coding again :D
Just to make this clear: You want to have both teleport and non teleport signs? I think, that could be sort of confusing, because you cannot tell whether a sign teleports you or not without using it.

I'm adding an option to limit the amount of waystones/signposts you are allowed to place, but I guess that is not what you meant. I'll think about it.

You can make a sign point directly at its destination, but that only works for teleport signposts (obviously).

**Comment by Zygus42** [comment]
Make non-teleport signs have a slightly different colour ?  
If you haven't placed them yourself and know which ones teleport you, then you deserve to have to click around :)
I just think that the signposts pointing to somewhere are a cool look which fits Minecraft's semi-Medieval look to a T.

**Comment by Gollorum** [comment]
The new version contains everything except the expensive recipes. I'll keep them in mind.

**Comment by Gollorum** [comment]
Hi, this is what I got so far:

-You can choose signpost and waystone recipes to be normal/expensive/very expensive/disabled
-expensive means one ender pearl instead of the middle sign for signposts/large signposts and three ender pearls+stone (instead of cobble) for waystones
-very expensive means one nether star for signposts/large signposts and one nether star for waystones
-expensive and very expensive recipes only craft one block each

Is this what you imagined?

**Comment by Zygus42** [comment]
Yep, sounds like this would allow server owners to customise nicely.  Well done.

**Comment by Gollorum** [comment]
The new version contains all your suggested features, so this can be closed :D
