### ISSUE TITLE
Not allowed to place signs?

### ISSUE THREAD

**Issue by Ash70** [Gollorum/Signpost#16]
Using version 1.11.2-1.05.1 with forge 2296.
I didn't change the config and relevant settings are thus:
```
I:maxSignposts=-1
  I:maxWaystones=-1
  S:signpostPermissionLevel=ALL
  S:waystonePermissionLevel=ALL
```
When placing a waystone (or sign) it removes the waystone from my inventory, but does not place it in world, in chat it says 'not allowed to place more waystones', then when rightclicking the spot where the waystone is supposed to be, will make it visible (but does not show the GUI) and then breaking the waystone will duplicate it in inventory.

**Comment by Gollorum** [comment]
Thank you for reporting the bug :D
I fixed it and released a new version. You propably loaded a map where an older version of this mod had been installed, and because of the bug, it saved that you have no waystones left to place.
You have to fix this manually by running these commands:
/setwaystonesleft -1
/setsignpostsleft -1
Sorry for the inconvenience :(
