### ISSUE TITLE
Food consumption in creative mode

### ISSUE THREAD

**Issue by forestbeing** [Gollorum/Signpost#19]
I encountered the issue that if you are in creative mode and travel using signposts, it still consumes
food. Since you cant view your food status in creative mode and normally dont consume any this behavior seems unintuitive. Even more, there can be a sudden death from starving if the player (me in that case, thats the reason im writing here :) ) switches back to normal game mode.
 If this is intended behavior i would be happy about a configuration parameter to stop food consuption in creative mode.

OFFTOPIC
PS: since i am a dev myself i would have added this in a pull request, but until now i have never compiled a java program with anything else than the standard tools and found myself to dumb to get the build to jar going. any tips if you like ;)
PPS: besides this small issue; awesome mod! way better immersive feeling than using command blocks (and less cumbersome to add)

**Comment by Gollorum** [comment]
Hey :D
Is it possible that you use harceroi's "signposts" mod?
In my mod ("signpost"), you only pay with items rather than food.
Anyway, disabling this in creative mode seems to be a good idea, so thank you for the suggestion :)

PS: I don't think I'm the best person to ask for help; I don't know your problem and there are plenty of tutorials and forums for this on the internet.
PPS: Thanks :D

**Comment by forestbeing** [comment]
Oh, this is embarassing. Sorry for the mix up.
Im glad my feedback was useful nontheless ;)

**Comment by Gollorum** [comment]
No problem ^^
