### ISSUE TITLE
StackOverflowError during ServerTickEvent

### ISSUE THREAD

**Issue by LlubNek** [Gollorum/Signpost#37]
This function, gollorum.signpost.blocks.SuperPostPost.getSuperTile(SuperPostPost.java:245), just keeps calling itself forever causing a stack overflow.

[latest.log](https://github.com/Gollorum/Signpost/files/3016829/latest.log)
[crash-2019-03-28_03.58.31-server.txt](https://github.com/Gollorum/Signpost/files/3016831/crash-2019-03-28_03.58.31-server.txt)

**Comment by LlubNek** [comment]
Here's the problem line: https://github.com/Gollorum/Signpost/blob/ddf382f6f5ba431802ae451e4b63223b461dbac2/src/main/java/gollorum/signpost/blocks/SuperPostPost.java#L245

Changing this line from `tile = getSuperTile(pos);` to `tile = pos.getTile();` should fix it.

**Comment by LlubNek** [comment]
Not sure what you're trying to do on line 244...

**Comment by Gollorum** [comment]
Fixed with version 1.08.1
I too am unsure what that line is supposed to do, but I am afraid something will break if I remove it. I think it had something to do with getTile() returning null if the chunk at that position was not loaded and me having no idea what I'm doing.
Anyway, thank you for pointing out this issue :D
